apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: nginx
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
