apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: nginx
        image: httpd:2.4
